"""estrutura inicial

Revision ID: 2a8f9b0b5763
Revises: 
Create Date: 2026-06-08 01:30:29.664580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8f9b0b5763'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.String(length=200), nullable=True),
    sa.Column('autor', sa.String(length=200), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('alerta', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mensagens_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_mensagens_grupo'), ['grupo'], unique=False)

    op.create_table('monitores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('usuario', sa.String(length=60), nullable=False),
    sa.Column('senha', sa.String(length=256), nullable=False),
    sa.Column('turno', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitores_usuario'), ['usuario'], unique=True)

    op.create_table('status_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ultima_verificacao_sistema', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rondas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('monitor_nome', sa.String(length=120), nullable=False),
    sa.Column('turno', sa.String(length=60), nullable=False),
    sa.Column('iniciada_em', sa.DateTime(), nullable=False),
    sa.Column('finalizada_em', sa.DateTime(), nullable=True),
    sa.Column('pasta', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rondas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rondas_monitor_id'), ['monitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rondas_status'), ['status'], unique=False)

    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ronda_id', sa.Integer(), nullable=True),
    sa.Column('nvr_id', sa.String(length=60), nullable=False),
    sa.Column('nvr_nome', sa.String(length=120), nullable=False),
    sa.Column('ufv', sa.String(length=120), nullable=True),
    sa.Column('local_preset', sa.String(length=120), nullable=False),
    sa.Column('pessoas', sa.Integer(), nullable=False),
    sa.Column('imagem_path', sa.Text(), nullable=True),
    sa.Column('detectado_em', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('tratativa', sa.Text(), nullable=True),
    sa.Column('responsavel', sa.String(length=120), nullable=True),
    sa.Column('tratado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ronda_id'], ['rondas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alertas_detectado_em'), ['detectado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_alertas_nvr_id'), ['nvr_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alertas_ronda_id'), ['ronda_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alertas_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alertas_ufv'), ['ufv'], unique=False)

    op.create_table('rondas_nvr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ronda_id', sa.Integer(), nullable=True),
    sa.Column('nvr_id', sa.String(length=60), nullable=False),
    sa.Column('nvr_nome', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('invasoes', sa.Integer(), nullable=False),
    sa.Column('pasta', sa.Text(), nullable=True),
    sa.Column('finalizada_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ronda_id'], ['rondas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rondas_nvr', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rondas_nvr_nvr_id'), ['nvr_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rondas_nvr_ronda_id'), ['ronda_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rondas_nvr', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rondas_nvr_ronda_id'))
        batch_op.drop_index(batch_op.f('ix_rondas_nvr_nvr_id'))

    op.drop_table('rondas_nvr')
    with op.batch_alter_table('alertas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alertas_ufv'))
        batch_op.drop_index(batch_op.f('ix_alertas_status'))
        batch_op.drop_index(batch_op.f('ix_alertas_ronda_id'))
        batch_op.drop_index(batch_op.f('ix_alertas_nvr_id'))
        batch_op.drop_index(batch_op.f('ix_alertas_detectado_em'))

    op.drop_table('alertas')
    with op.batch_alter_table('rondas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rondas_status'))
        batch_op.drop_index(batch_op.f('ix_rondas_monitor_id'))

    op.drop_table('rondas')
    op.drop_table('status_sistema')
    with op.batch_alter_table('monitores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitores_usuario'))

    op.drop_table('monitores')
    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mensagens_grupo'))
        batch_op.drop_index(batch_op.f('ix_mensagens_data'))

    op.drop_table('mensagens')
    # ### end Alembic commands ###
