"""adiciona nvr_status_log, camera_status_log e monitor_event

Revision ID: bfa29634ec18
Revises: b38ae738e769
Create Date: 2026-06-28 06:30:58.587079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa29634ec18'
down_revision = 'b38ae738e769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_status_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nvr_id', sa.String(length=120), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('signal_ok', sa.Boolean(), nullable=False),
    sa.Column('recording', sa.Boolean(), nullable=False),
    sa.Column('bit_rate_kbps', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('camera_status_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_camera_status_log_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_camera_status_log_nvr_id'), ['nvr_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_camera_status_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('monitor_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alvo_tipo', sa.String(length=20), nullable=False),
    sa.Column('nvr_id', sa.String(length=120), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('nome_exibicao', sa.String(length=200), nullable=False),
    sa.Column('severidade', sa.String(length=20), nullable=False),
    sa.Column('chave_problema', sa.String(length=120), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('aberto_em', sa.DateTime(), nullable=False),
    sa.Column('resolvido_em', sa.DateTime(), nullable=True),
    sa.Column('notificado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitor_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitor_event_aberto_em'), ['aberto_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitor_event_alvo_tipo'), ['alvo_tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitor_event_nvr_id'), ['nvr_id'], unique=False)

    op.create_table('nvr_status_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nvr_id', sa.String(length=120), nullable=False),
    sa.Column('nvr_nome', sa.String(length=200), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('health', sa.String(length=20), nullable=False),
    sa.Column('reachable', sa.Boolean(), nullable=False),
    sa.Column('cameras_total', sa.Integer(), nullable=False),
    sa.Column('cameras_online', sa.Integer(), nullable=False),
    sa.Column('cameras_offline', sa.Integer(), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nvr_status_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nvr_status_log_nvr_id'), ['nvr_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nvr_status_log_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nvr_status_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nvr_status_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_nvr_status_log_nvr_id'))

    op.drop_table('nvr_status_log')
    with op.batch_alter_table('monitor_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitor_event_nvr_id'))
        batch_op.drop_index(batch_op.f('ix_monitor_event_alvo_tipo'))
        batch_op.drop_index(batch_op.f('ix_monitor_event_aberto_em'))

    op.drop_table('monitor_event')
    with op.batch_alter_table('camera_status_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_camera_status_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_camera_status_log_nvr_id'))
        batch_op.drop_index(batch_op.f('ix_camera_status_log_channel_id'))

    op.drop_table('camera_status_log')
    # ### end Alembic commands ###
