"""adiciona camera_status_log e monitor_event

Revision ID: b38ae738e769
Revises: 2a8f9b0b5763
Create Date: 2026-06-28 06:00:20.033120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b38ae738e769'
down_revision = '2a8f9b0b5763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nvr_monitorado')
    with op.batch_alter_table('nvr_presets', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_nvr_presets_nvr_numero', ['nvr_id', 'numero'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nvr_presets', schema=None) as batch_op:
        batch_op.drop_constraint('uq_nvr_presets_nvr_numero', type_='unique')
        batch_op.alter_column('nome',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    op.create_table('nvr_monitorado',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nvr_id', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('site', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('ip', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('porta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('use_https', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('usuario', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('senha', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('nvr_monitorado_pkey')),
    sa.UniqueConstraint('nvr_id', name=op.f('nvr_monitorado_nvr_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
